version: "3.9"

services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - local

networks:
  local:
    driver: bridge
