version: "3.9"

services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    networks:
      - local

networks:
  local:
    driver: bridge
